### ISSUE TITLE
is there a way to compose a schema out of multiple smaller schemas?

### ISSUE THREAD

**Issue by neongrau** [parrish/json-schema_builder#11]
Hey!

I'm trying to split up the rather clunky schema for JSONAPI into parts and combine them per use case.

It seems possible to assign a nested object definition as items to any array.
But when i try to add an object to another object with a name it's properties stay empty

```
{"type"=>:object, "properties"=>{"data"=>{"type"=>"object", "properties"=>{}}}}
``` 

Is there a way or would i have to add something like a properties method to object that behave like items on array ?

Thanks,
Ralf

**Comment by neongrau** [comment]
nvm if finally figured it out, i just need to define my schema partials to return procs and i then can compose them the way i need.

```ruby
def schema_partial
  Proc.new {
    string :id
    string :type
    object :attributes
      string :id
      string :title
      string :created_at
    end
  }
end

def schema(single:false)
  if single
    object :data, &schema_partial
  else
    object do
      array :data do
        items object &schema_partial
      end
    end
  end
end
```

**Comment by markkvdb** [comment]
Thank you for sharing the solution! I was looking how to handle decomposability. Your solution works great :)
