### ISSUE TITLE
Feature request: Ability to extend JSON Schema, eg. additional keywords

### ISSUE THREAD

**Issue by Mtihc** [parrish/json-schema_builder#13]
It would be nice if we were able to add additional keywords, like

```ruby
object do
  string :name
  string :notes, 'x-scope': :admin
end
```

In this example I'm adding a key called `x-scope`, to indicate that it's a custom attribute. But it might as well be `scope` without the `x-`.

The resulting JSON would look like this

```json
{
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "notes": { "type": "string", "x-scope": "admin" }
  }
}
```

This is allowed according to the spec. See chapter "Extending JSON Schema". Although it's in draft, if I'm correct.
https://json-schema.org/draft/2019-09/json-schema-core.html#extending

Do you think this is something you'd like to add?

If yes, I'm willing to implement it and create a Pull Request.

**Comment by ngouy** [comment]
you can do that with monkey patching.

Here is how I introduced support for deprecated for example:

```rb
# initializers/json_schema.rb

module JSON
  module SchemaBuilder
    class Entity
      attribute :deprecated
    end
  end
end
```

**Comment by Mtihc** [comment]
Oh, nice. Thanks.
