### ISSUE TITLE
Allow for builder-style DSL

### ISSUE THREAD

**Issue by Haniyya** [parrish/json-schema_builder#4]
First, great gem!

It would be nice though to be able to pass Instances of Builders ( for example `JSON::SchemaBuilder::Object`) around and build them up from the outside. Example:

```ruby
def post(obj)
  obj.string :title
  obj.string :body
end

obj = JSON::SchemaBuilder::Object.new
post(obj)
```

This way you could keep your definition logic in POROs (which some prefer).
I realize this is already somewhat possible, but the Builders Schema is only updated on initialization (as far as I can see).
So simply updating at each `entity` call could be enough.

**Comment by parrish** [comment]
:wave: Thanks!   😀

I _think_ we could just re-initialize the children of the object after adding new ones:

``` ruby
obj.as_json["properties"] # => {"author"=>{"type"=>"string"}}
obj.string :title
obj.string :body
obj.as_json["properties"] # => {"author"=>{"type"=>"string"}}
obj.initialize_children
obj.as_json["properties"] # => {"author"=>{"type"=>"string"}, "title"=>{"type"=>"string"}, "body"=>{"type"=>"string"}}
```

I'm not 100% sure of how it should be have when modifying nested schemas e.g. the current behavior is:

``` ruby
obj.as_json["properties"] # => {"preferences"=>{"type"=>"object", "properties"=>{"email_frequency"=>{"type"=>"string"}}}}

obj.object :preferences do
  boolean :email_enabled
end

obj.initalize_children

# The preferences property is replaced:
obj.as_json["properties"] # => "preferences"=>{"type"=>"object", "properties"=>{"email_enabled"=>{"type"=>"boolean"}}}}
```

I'm not sure whether it's better to replace that property or "reopen it" when modifying.  What do you think?

**Comment by Haniyya** [comment]
@parrish I think in the spirit of continuous building and passing builder-objects to functions, nested schemas should be mutated instead of being replaced.

But I think there is a case to be made for replacing them if need be. Is this possible right now?

**Comment by parrish** [comment]
Yeah, I agree that re-opening the objects to mutate them is probably more intuitive.

The current behavior (after calling `initalize_children`) is to replace the property.

I'll give it a shot and see how involved it would be to implement.  If nothing else, I'll set it up to automatically re-initialize after adding child properties.

**Comment by Haniyya** [comment]
@parrish Thanks! That'll be very useful. If you don't find the time, I might dive in this weekende and have a look myself.

**Comment by parrish** [comment]
:wave: Could you take a look at #8 and see if this seems like a reasonable implementation?
