### ISSUE TITLE
Usage of any_of with array items

### ISSUE THREAD

**Issue by Stex** [parrish/json-schema_builder#6]
Hey! First of all, thank you for providing a (currently: the) DSL to generate JSON schemas in Ruby!

**I solved this problem by now (see below), but I'll  include my original issue message here anyway as it might make for a good addition to the examples**

---

I ran into a problem today when describing a rather complex schema that included an array of polymorphic objects.

From my understanding of JSON schema, it should be possible to simply define "items" using the `"anyOf"` keyword and then specifying the various objects which might occur as array items. I built a small example:

```ruby
class MySchema
  require 'json/schema_builder'
  include JSON::SchemaBuilder

  def schema
    object do
      array :an_array do
        items do
          any_of [
            object { string(:name) },
            object { number(:age) }
          ]
        end
      end
    end
  end
end

puts JSON.pretty_generate(MySchema.new.schema.as_json)
```

This indeed generates a corresponding `anyOf`, but it also adds a `type` and `properties` to `items`:

```json
{
  "type": "object",
  "properties": {
    "an_array": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "age": {
                "type": "number"
              }
            }
          }
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "age": {
            "type": "number"
          }
        }
      }
    }
  }
}
```

I also tried to give `items` an explicit `type: :object` which got rid of the additonal keys, but always included an additional empty object definition inside `anyOf`:

```json
{
  "type": "object",
  "properties": {
    "an_array": {
      "type": "array",
      "items": {
        "anyOf": [
          {
            "type": "object",
            "properties": {
            }
          },
          {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              }
            }
          },
          {
            "type": "object",
            "properties": {
              "age": {
                "type": "number"
              }
            }
          }
        ]
      }
    }
  }
}
```

---

**Solution**:

I solved this now by specifying the possible objects using

```ruby
items any_of: [
  object { string(:name) },
  object { number(:age) }
]
```

which results in the correct output.

Shouldn't `any_of` as an option to `items` and when being used inside `items` have the same result? At least it looked this way from the terse/verbose examples.

**Comment by parrish** [comment]
:wave: Thanks!  I'm glad it's useful!

Yep, that's definitely a bug.  I'll build a spec from your example and get a fix up shortly.

**Comment by parrish** [comment]
Just pushed a fix and I'll cut a new release later today :+1:
